# Generated by Django 4.0.4 on 2022-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekApp', '0005_tag_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(to='geekApp.tag'),
        ),
    ]
