# Generated by Django 4.0.4 on 2022-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekApp', '0007_blogpost_you_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='you',
            field=models.CharField(max_length=100),
        ),
    ]
